# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_0 || ORIG_REF_NAME==design_2_microblaze_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_0 || ORIG_REF_NAME==design_2_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_0 || ORIG_REF_NAME==design_2_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_0/design_2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_0/design_2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_lmb_bram_0/design_2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_0 || ORIG_REF_NAME==design_2_lmb_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_mdm_1_0 || ORIG_REF_NAME==design_2_mdm_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_0 || ORIG_REF_NAME==design_2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_clk_wiz_1_100M_0/design_2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_axi_periph_0/design_2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_copro_0_8/design_2_copro_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_copro_0_8 || ORIG_REF_NAME==design_2_copro_0_8} -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_0 || ORIG_REF_NAME==design_2_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_lmb_bram_0/design_2_lmb_bram_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_mdm_1_0 || ORIG_REF_NAME==design_2_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_0 || ORIG_REF_NAME==design_2_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_0 || ORIG_REF_NAME==design_2_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_1_100M_0/design_2_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_1_100M_0/design_2_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica2/hw/Practica2/Practica2.gen/sources_1/bd/design_2/design_2_ooc.xdc
