# VGA
set_property PACKAGE_PIN G19 [get_ports {blue_0[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[0]}]
set_property PACKAGE_PIN H19 [get_ports {blue_0[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[1]}]
set_property PACKAGE_PIN J19 [get_ports {blue_0[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[2]}]
set_property PACKAGE_PIN N19 [get_ports {blue_0[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[3]}]
set_property PACKAGE_PIN N18 [get_ports {red_0[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[0]}]
set_property PACKAGE_PIN L18 [get_ports {red_0[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[1]}]
set_property PACKAGE_PIN K18 [get_ports {red_0[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[2]}]
set_property PACKAGE_PIN J18 [get_ports {red_0[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[3]}]
set_property PACKAGE_PIN J17 [get_ports {green_0[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[0]}]
set_property PACKAGE_PIN H17 [get_ports {green_0[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[1]}]
set_property PACKAGE_PIN G17 [get_ports {green_0[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[2]}]
set_property PACKAGE_PIN D17 [get_ports {green_0[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[3]}]
set_property PACKAGE_PIN P19 [get_ports hsyncb_0]						
	set_property IOSTANDARD LVCMOS33 [get_ports hsyncb_0]
set_property PACKAGE_PIN R19 [get_ports vsyncb_0]						
	set_property IOSTANDARD LVCMOS33 [get_ports vsyncb_0]
	
	
## Switches -> ffffcccc
set_property PACKAGE_PIN V17 [get_ports {max_col_0[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_col_0[0]}]
set_property PACKAGE_PIN V16 [get_ports {max_col_0[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_col_0[1]}]
set_property PACKAGE_PIN W16 [get_ports {max_col_0[2]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {max_col_0[2]}]
set_property PACKAGE_PIN W17 [get_ports {max_col_0[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_col_0[3]}]
	
set_property PACKAGE_PIN W15 [get_ports {max_row_0[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_row_0[0]}]
set_property PACKAGE_PIN V15 [get_ports {max_row_0[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_row_0[1]}]
set_property PACKAGE_PIN W14 [get_ports {max_row_0[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_row_0[2]}]
set_property PACKAGE_PIN W13 [get_ports {max_row_0[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {max_row_0[3]}]