# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DesignP1/DesignP1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1 || ORIG_REF_NAME==DesignP1} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_microblaze_0_0/DesignP1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_microblaze_0_0 || ORIG_REF_NAME==DesignP1_microblaze_0_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_dlmb_v10_0/DesignP1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_dlmb_v10_0 || ORIG_REF_NAME==DesignP1_dlmb_v10_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_ilmb_v10_0/DesignP1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_ilmb_v10_0 || ORIG_REF_NAME==DesignP1_ilmb_v10_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_dlmb_bram_if_cntlr_0/DesignP1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DesignP1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_ilmb_bram_if_cntlr_0/DesignP1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DesignP1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_lmb_bram_0/DesignP1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_lmb_bram_0 || ORIG_REF_NAME==DesignP1_lmb_bram_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_mdm_1_0/DesignP1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_mdm_1_0 || ORIG_REF_NAME==DesignP1_mdm_1_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_clk_wiz_1_0/DesignP1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_clk_wiz_1_0 || ORIG_REF_NAME==DesignP1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_rst_clk_wiz_1_100M_0/DesignP1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DesignP1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_axi_gpio_0_0/DesignP1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_axi_gpio_0_0 || ORIG_REF_NAME==DesignP1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_axi_uartlite_0_0/DesignP1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_axi_uartlite_0_0 || ORIG_REF_NAME==DesignP1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_xbar_0/DesignP1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_xbar_0 || ORIG_REF_NAME==DesignP1_xbar_0} -quiet] -quiet

# IP: bd/DesignP1/ip/DesignP1_microblaze_0_axi_periph_0/DesignP1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DesignP1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DesignP1_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_microblaze_0_0/DesignP1_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_microblaze_0_0 || ORIG_REF_NAME==DesignP1_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_microblaze_0_0/DesignP1_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_lmb_bram_0/DesignP1_lmb_bram_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_mdm_1_0/DesignP1_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_mdm_1_0 || ORIG_REF_NAME==DesignP1_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_mdm_1_0/DesignP1_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_clk_wiz_1_0/DesignP1_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_clk_wiz_1_0 || ORIG_REF_NAME==DesignP1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_clk_wiz_1_0/DesignP1_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_clk_wiz_1_0 || ORIG_REF_NAME==DesignP1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_clk_wiz_1_0/DesignP1_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_rst_clk_wiz_1_100M_0/DesignP1_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DesignP1_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_rst_clk_wiz_1_100M_0/DesignP1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DesignP1_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_axi_gpio_0_0/DesignP1_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_axi_gpio_0_0 || ORIG_REF_NAME==DesignP1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_axi_gpio_0_0/DesignP1_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_axi_gpio_0_0/DesignP1_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_axi_gpio_0_0 || ORIG_REF_NAME==DesignP1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_axi_uartlite_0_0/DesignP1_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_axi_uartlite_0_0 || ORIG_REF_NAME==DesignP1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_axi_uartlite_0_0/DesignP1_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/ip/DesignP1_axi_uartlite_0_0/DesignP1_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DesignP1_axi_uartlite_0_0 || ORIG_REF_NAME==DesignP1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practica1/Practica1.gen/sources_1/bd/DesignP1/DesignP1_ooc.xdc
