# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const_but.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_1/design_2_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_1 || ORIG_REF_NAME==design_2_microblaze_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_v10_1/design_2_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_1 || ORIG_REF_NAME==design_2_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_v10_1/design_2_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_1 || ORIG_REF_NAME==design_2_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_1/design_2_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_1/design_2_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_lmb_bram_1/design_2_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_1 || ORIG_REF_NAME==design_2_lmb_bram_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mdm_1_1/design_2_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_mdm_1_1 || ORIG_REF_NAME==design_2_mdm_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_1_1/design_2_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_1 || ORIG_REF_NAME==design_2_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_clk_wiz_1_100M_1/design_2_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_uartlite_0_1/design_2_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_1 || ORIG_REF_NAME==design_2_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_1/design_2_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_1 || ORIG_REF_NAME==design_2_xbar_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_axi_periph_1/design_2_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_2_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_copro_0_2/design_2_copro_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_copro_0_2 || ORIG_REF_NAME==design_2_copro_0_2} -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_1/design_2_microblaze_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_1 || ORIG_REF_NAME==design_2_microblaze_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_1/design_2_microblaze_0_1_ooc_debug.xdc

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_lmb_bram_1/design_2_lmb_bram_1_ooc.xdc

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_mdm_1_1/design_2_mdm_1_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_mdm_1_1 || ORIG_REF_NAME==design_2_mdm_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_mdm_1_1/design_2_mdm_1_1_ooc_trace.xdc

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_1_1/design_2_clk_wiz_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_1 || ORIG_REF_NAME==design_2_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_1_1/design_2_clk_wiz_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_1 || ORIG_REF_NAME==design_2_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_1_1/design_2_clk_wiz_1_1_ooc.xdc

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_1_100M_1/design_2_rst_clk_wiz_1_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_1_100M_1/design_2_rst_clk_wiz_1_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_1/design_2_axi_uartlite_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_1 || ORIG_REF_NAME==design_2_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_1/design_2_axi_uartlite_0_1_ooc.xdc

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_1/design_2_axi_uartlite_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_1 || ORIG_REF_NAME==design_2_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/usuario_local/Documents/Practicas_SE/Practica_2/Practica_2.gen/sources_1/bd/design_2/design_2_ooc.xdc
