# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/design_final/design_final.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final || ORIG_REF_NAME==design_final} -quiet] -quiet

# IP: bd/design_final/ip/design_final_microblaze_0_0/design_final_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_microblaze_0_0 || ORIG_REF_NAME==design_final_microblaze_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_dlmb_v10_0/design_final_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_dlmb_v10_0 || ORIG_REF_NAME==design_final_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_ilmb_v10_0/design_final_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_ilmb_v10_0 || ORIG_REF_NAME==design_final_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_dlmb_bram_if_cntlr_0/design_final_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_final_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_ilmb_bram_if_cntlr_0/design_final_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_final_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_lmb_bram_0/design_final_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_lmb_bram_0 || ORIG_REF_NAME==design_final_lmb_bram_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_mdm_1_0/design_final_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_mdm_1_0 || ORIG_REF_NAME==design_final_mdm_1_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_clk_wiz_1_0/design_final_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_clk_wiz_1_0 || ORIG_REF_NAME==design_final_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_rst_clk_wiz_1_100M_0/design_final_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_final_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_led_0_0/design_final_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_led_0_0 || ORIG_REF_NAME==design_final_led_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_keypad_0_0/design_final_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_keypad_0_0 || ORIG_REF_NAME==design_final_keypad_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_matriz_0_0/design_final_matriz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_matriz_0_0 || ORIG_REF_NAME==design_final_matriz_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_xbar_0/design_final_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_xbar_0 || ORIG_REF_NAME==design_final_xbar_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_microblaze_0_axi_periph_0/design_final_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_final_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_vga_0_0/design_final_vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_vga_0_0 || ORIG_REF_NAME==design_final_vga_0_0} -quiet] -quiet

# IP: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_vga_0_0/src/clk_ip_core/clk_ip_core.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_ip_core || ORIG_REF_NAME==clk_ip_core} -quiet] -quiet

# IP: bd/design_final/ip/design_final_axi_gpio_0_0/design_final_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_axi_gpio_0_0 || ORIG_REF_NAME==design_final_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_microblaze_0_0/design_final_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_microblaze_0_0 || ORIG_REF_NAME==design_final_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_microblaze_0_0/design_final_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_lmb_bram_0/design_final_lmb_bram_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_mdm_1_0/design_final_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_mdm_1_0 || ORIG_REF_NAME==design_final_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_mdm_1_0/design_final_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_clk_wiz_1_0/design_final_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_clk_wiz_1_0 || ORIG_REF_NAME==design_final_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_clk_wiz_1_0/design_final_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_clk_wiz_1_0 || ORIG_REF_NAME==design_final_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_clk_wiz_1_0/design_final_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_rst_clk_wiz_1_100M_0/design_final_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_final_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_rst_clk_wiz_1_100M_0/design_final_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_final_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_vga_0_0/src/clk_ip_core/clk_ip_core.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_ip_core || ORIG_REF_NAME==clk_ip_core} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_vga_0_0/src/clk_ip_core/clk_ip_core_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_axi_gpio_0_0/design_final_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_axi_gpio_0_0 || ORIG_REF_NAME==design_final_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_axi_gpio_0_0/design_final_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/ip/design_final_axi_gpio_0_0/design_final_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_final_axi_gpio_0_0 || ORIG_REF_NAME==design_final_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/5_QUINTO/SE/Practicas_SE/ProyectoFinal/hw/proyectoFinal.gen/sources_1/bd/design_final/design_final_ooc.xdc
