# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/design_3/design_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_microblaze_0_0/design_3_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_microblaze_0_0 || ORIG_REF_NAME==design_3_microblaze_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_dlmb_v10_0 || ORIG_REF_NAME==design_3_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ilmb_v10_0/design_3_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_ilmb_v10_0 || ORIG_REF_NAME==design_3_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_dlmb_bram_if_cntlr_0/design_3_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_3_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ilmb_bram_if_cntlr_0/design_3_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_3_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_lmb_bram_0/design_3_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_lmb_bram_0 || ORIG_REF_NAME==design_3_lmb_bram_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_mdm_1_0/design_3_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_mdm_1_0 || ORIG_REF_NAME==design_3_mdm_1_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_clk_wiz_1_0/design_3_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_clk_wiz_1_0 || ORIG_REF_NAME==design_3_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rst_clk_wiz_1_100M_0/design_3_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_3_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_0/design_3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xbar_0 || ORIG_REF_NAME==design_3_xbar_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_microblaze_0_axi_periph_0/design_3_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_3_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_uartlite_0_0 || ORIG_REF_NAME==design_3_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_keypad_0_0/design_3_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_keypad_0_0 || ORIG_REF_NAME==design_3_keypad_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_led_0_1/design_3_led_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_led_0_1 || ORIG_REF_NAME==design_3_led_0_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_led_1_1/design_3_led_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_led_1_1 || ORIG_REF_NAME==design_3_led_1_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_led_2_1/design_3_led_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_led_2_1 || ORIG_REF_NAME==design_3_led_2_1} -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_microblaze_0_0/design_3_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_microblaze_0_0 || ORIG_REF_NAME==design_3_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_microblaze_0_0/design_3_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_lmb_bram_0/design_3_lmb_bram_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_mdm_1_0/design_3_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_mdm_1_0 || ORIG_REF_NAME==design_3_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_mdm_1_0/design_3_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_clk_wiz_1_0/design_3_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_clk_wiz_1_0 || ORIG_REF_NAME==design_3_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_clk_wiz_1_0/design_3_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_clk_wiz_1_0 || ORIG_REF_NAME==design_3_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_clk_wiz_1_0/design_3_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_rst_clk_wiz_1_100M_0/design_3_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_3_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_rst_clk_wiz_1_100M_0/design_3_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_3_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_xbar_0/design_3_xbar_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_axi_uartlite_0_0 || ORIG_REF_NAME==design_3_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_3_axi_uartlite_0_0 || ORIG_REF_NAME==design_3_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/oscar/OneDrive/Documentos/UCM/QUINTO/SE/Practicas_SE/Practica3/hw/Practica3/Practica3.gen/sources_1/bd/design_3/design_3_ooc.xdc
